[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  # Usa as variáveis definidas com escopo 'Production' no painel
  command = "npm run build"

[context.dev]
  # Usa as variáveis definidas com escopo 'Development' no painel
  command = "npm run build"