version: '3.8'

services:
  boletim:
    image: davs933/boletim-pib:v1
    container_name: boletim_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boletim.rule=Host(`boletim.pibsaomiguel.com.br`)"
      - "traefik.http.routers.boletim.entrypoints=websecure"
      - "traefik.http.routers.boletim.tls=true"
      - "traefik.http.routers.boletim.tls.certresolver=letsencrypt"
      # O Traefik vai encaminhar o tráfego para a porta definida aqui
      - "traefik.http.services.boletim.loadbalancer.server.port=3000"

networks:
  web:
    external: true
